export interface IDataSeafarer {
  Id: number
  KinName: any
  KinPhone: any
  KinEmail: any
  PassPortIssueDate: string
  EmpId: number
  VisaSponsorId: number
  Remarks: string
  VisaIssueDate: string
  VisaExpiryDate: string
  EmployeeName: string
  SponsorName: string
  EmployeeCode: string
  JobName: string
  Nationality: string
  BirthDate: string
  Phone: string
  Mobile: string
  Email: string
  NationalId: string
  EmploymentDate: string
  InsuranceDate: string
  PassportExpireDate: any
  PassportNumber: string
  Age: string
  EmployeeNameAR: string
  EmployeeNameEN: string
  JobNameEN: string
  JobNameAR: string
  Salary: number
  Address: string
  Gender: string
  Religion: string
  InsuranceNumber: string
  Area: any
  MilitaryServiceExpireDate: string
  SyndicateCardNumber: string
  SyndicateExpirationDate: any
  BusinessPhone: any
  BirthPlace: string
  NationalIdExpiryDate: string
  Company: string
  PostCategoryLevel: any
  Tier: any
  DrivingLicenseNumber: any
  WorkPermit: any
  PermitNumber: any
  BloodType: any
  WorkLocation: string
  PermitExpirationDate: any
  Notes: any
  MedicalInsuranceAmount: number
  InsuranceTitle: any
  InsuranceOffice: string
  MedicalInsuranceNo: any
  MedicalInsuranceDate: any
  GraduationYear: string
  PostGraduateDegree: any
  PostGraduateUniversity: string
  PostGraduateSpecialty: any
  PostGraduateGrade: any
  PropationEndDate: string
  EmpManager: string
  NameOfSpouse: string
  NoOfChildren: number
  BodyWeight: number
  Height: number
  VisaUAEIdNO: string
  NearestAirport: string
  ResidenceNumber: string
  SkypeID: string
  PermanentAddressHomeCountry: string
  ContactNumberHomeCountry: string
  ContactNameAndNumberDuringEmergenciesUAE: string
  ContactNameAndNumberDuringEmergenciesHome: string
  SeamanBookNO: string
  SeamanIssueDate: string
  SeamanExpiryDate: string
  CicpaNO: string
  CicpaIssueDate: string
  CicpaExpiryDate: string
  Declaration: string
  SignedOffFromAShipDueToMedicalReason: boolean
  SignedOffFromAShipDueToMedicalReasonComment: string
  UndergoneAnyMdicalOperation: boolean
  UndergoneAnyMdicalOperationComment: string
  DoctorConsultation: boolean
  DoctorConsultationComment: string
  HealthOrDisabilityProblem: boolean
  HealthOrDisabilityProblemComment: string
  InquiryOrInvolvedMaritimeAccident: boolean
  InquiryOrInvolvedMaritimeAccidentComment: string
  LicenseSuspendedOrRevoked: boolean
  LicenseSuspendedOrRevokedComment: string
  ConfirmationInsuranceDate: any
  MaritalStatus: string
  Status: number
  Basic: any
  Advanced: any
  FullLicence: any
  Maintenance: any

}
